import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyShop" model, go to https://seetext-exit-intent.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v1",
  storageKey: "DataModel-Shopify-Shop",
  fields: {
    averageOrderValue: {
      type: "number",
      default: 85.53,
      storageKey: "nfIs6s_Wk9To",
    },
    firstEmail: { type: "boolean", storageKey: "jsekYiNsnZrJ" },
    firstSave: { type: "boolean", storageKey: "4s8-YdvIH7RL" },
    inSetup: {
      type: "boolean",
      default: true,
      storageKey: "4jDpem3ooobA",
    },
    isSubscribed: {
      type: "boolean",
      default: false,
      storageKey: "KrPt4wlZ0uKb",
    },
    mantleApiToken: { type: "string", storageKey: "IzQNK7GfnNnG" },
    pixelAccountId: {
      type: "string",
      default: "",
      storageKey: "SJbcPyopPil7",
    },
    popupActivationPixels: {
      type: "hasMany",
      children: {
        model: "popupActivationPixel",
        belongsToField: "shop",
      },
      storageKey: "cHsH_KyyATPw",
    },
    popupCheckoutPixels: {
      type: "hasMany",
      children: {
        model: "popupCheckoutPixel",
        belongsToField: "shop",
      },
      storageKey: "xlOT_iQRzywD",
    },
    popupConditions: {
      type: "hasOne",
      child: { model: "popupConditions", belongsToField: "shop" },
      storageKey: "F9cpVLXtJU7l",
    },
    popupContent: {
      type: "hasOne",
      child: { model: "popupContent", belongsToField: "shop" },
      storageKey: "5-PJTBOuVLI9",
    },
    popupEmails: {
      type: "hasMany",
      children: { model: "popupEmails", belongsToField: "shop" },
      storageKey: "Q2lr6stHj6Kp",
    },
    popupIdentifier: {
      type: "string",
      shopifyMetafield: {
        privateMetafield: false,
        namespace: "$app:seetext-popup",
        key: "popupParameters",
        metafieldType: "single_line_text_field",
        allowMultipleEntries: false,
      },
      validations: { unique: true },
      storageKey: "0OH0wm_YeRrR",
    },
    popupStyling: {
      type: "hasOne",
      child: { model: "popupStyling", belongsToField: "shop" },
      storageKey: "K-howBc_SV1p",
    },
    showReviewPopup: {
      type: "boolean",
      default: true,
      storageKey: "kuIX4AqpGJ8M",
    },
    totalEmails: {
      type: "computed",
      sourceFile: "api/models/shopifyShop/totalEmails.gelly",
      storageKey: "L2kNh9MggL94",
    },
  },
  shopify: {
    fields: [
      "address1",
      "address2",
      "appInstallations",
      "checkoutApiSupported",
      "city",
      "cookieConsentLevel",
      "country",
      "countryCode",
      "countryName",
      "countyTaxes",
      "currency",
      "customerAccountsV2",
      "customerEmail",
      "customers",
      "discounts",
      "domain",
      "eligibleForCardReaderGiveaway",
      "eligibleForPayments",
      "email",
      "enabledPresentmentCurrencies",
      "finances",
      "forceSsl",
      "gdprRequests",
      "googleAppsDomain",
      "googleAppsLoginEnabled",
      "hasDiscounts",
      "hasGiftCards",
      "hasStorefront",
      "ianaTimezone",
      "latitude",
      "longitude",
      "marketingSmsContentEnabledAtCheckout",
      "moneyFormat",
      "moneyInEmailsFormat",
      "moneyWithCurrencyFormat",
      "moneyWithCurrencyInEmailsFormat",
      "multiLocationEnabled",
      "myshopifyDomain",
      "name",
      "passwordEnabled",
      "phone",
      "planDisplayName",
      "planName",
      "preLaunchEnabled",
      "primaryLocale",
      "province",
      "provinceCode",
      "requiresExtraPaymentsAgreement",
      "setupRequired",
      "shopOwner",
      "shopifyCreatedAt",
      "shopifyUpdatedAt",
      "source",
      "syncs",
      "taxShipping",
      "taxesIncluded",
      "timezone",
      "transactionalSmsDisabled",
      "weightUnit",
      "zipCode",
    ],
  },
};
